<?php

declare(strict_types=1);

namespace JobWarden\Tests\Models;

use JobWarden\Models\Job;
use JobWarden\Models\JobAttempt;
use JobWarden\Models\JobEvent;
use JobWarden\States\ActorType;
use JobWarden\States\AttemptState;
use JobWarden\States\JobState;
use JobWarden\Tests\Concerns\RefreshesJobWardenSchema;
use JobWarden\Tests\TestCase;
use Symfony\Component\Uid\Uuid;

final class ModelTest extends TestCase
{
    use RefreshesJobWardenSchema;

    protected function setUp(): void
    {
        parent::setUp();
        $this->setUpJobWardenSchema();
    }

    public function test_job_gets_a_uuidv7_key_and_casts_round_trip(): void
    {
        $job = Job::create([
            'job_class' => 'App\\Jobs\\Demo',
            'state' => JobState::Queued,
            'idempotent' => true,
            'params' => ['order_id' => 42, 'nested' => ['a' => 1]],
        ]);

        // UUIDv7: a valid, version-7, string key generated by the model.
        // Symfony parses a v7 string into a UuidV7 instance — that *is* the
        // version proof.
        $this->assertIsString($job->id);
        $this->assertTrue(Uuid::isValid($job->id));
        $this->assertInstanceOf(\Symfony\Component\Uid\UuidV7::class, Uuid::fromString($job->id));
        $this->assertFalse($job->getIncrementing());

        $fresh = Job::on(config('jobwarden.connection'))->find($job->id);
        $this->assertInstanceOf(JobState::class, $fresh->state);
        $this->assertSame(JobState::Queued, $fresh->state);
        $this->assertTrue($fresh->idempotent);
        $this->assertSame(['order_id' => 42, 'nested' => ['a' => 1]], $fresh->params);
    }

    public function test_job_uses_the_dedicated_connection_and_prefix(): void
    {
        $job = Job::create(['job_class' => 'X', 'state' => JobState::Pending]);

        $this->assertSame(config('jobwarden.connection'), $job->getConnectionName());
        $this->assertSame($this->tbl('jobs'), $job->getTable());
    }

    public function test_relationships_resolve(): void
    {
        $job = Job::create(['job_class' => 'X', 'state' => JobState::Running, 'attempt_count' => 1]);

        $attempt = JobAttempt::create([
            'job_id' => $job->id,
            'attempt_number' => 1,
            'state' => AttemptState::Running,
            'fencing_token' => 1,
        ]);

        JobEvent::create([
            'job_id' => $job->id,
            'attempt_id' => $attempt->id,
            'level' => 'attempt',
            'from_state' => 'dispatched',
            'to_state' => 'running',
            'actor_type' => ActorType::Worker,
            'context' => ['fencing_token' => 1],
            'created_at' => now(),
        ]);

        $this->assertCount(1, $job->attempts()->get());
        $this->assertSame(AttemptState::Running, $job->attempts()->first()->state);
        $this->assertSame($job->id, $attempt->job->id);

        $event = $job->events()->first();
        $this->assertSame(ActorType::Worker, $event->actor_type);
        $this->assertSame(['fencing_token' => 1], $event->context);
        // bigint monotonic id on the append-only table.
        $this->assertIsInt($event->id);
    }
}
